export const SEND_PACKETS_TYPES = {
    UPDATE_PROGRESS_VALUE: 'sendPackets/UPDATE_PROGRESS_VALUE',
    SET_MAX_PROGRESS_VALUE: 'sendPackets/SET_MAX_PROGRESS_VALUE',
    SET_FILE: 'sendPackets/SET_FILE',
    SET_NIC: 'sendPackets/SET_NIC'
}